### ISSUE TITLE
It doesn't work as desired on devices like android / iphone it appears as one text box on these devices

### ISSUE THREAD

**Issue by ajeets1978** [fkranenburg/bootstrap-pincode-input#2]

**Comment by ajeets1978** [comment]
<img width="319" alt="screen shot 2016-09-07 at 11 40 18 am" src="https://cloud.githubusercontent.com/assets/4997895/18296854/f3bfed8a-74ef-11e6-87e0-4e50e82bda03.png">

**Comment by LordZombi** [comment]
I have the same issue. I found out that JS code one the DEMO page is different than JS code in this repo. So if you want a quickfix just copy JS from demo page.

Keep DEMO code ano REPO code synced please :)

**Comment by fkranenburg** [comment]
@LordZombi Are you sure? I didn't find any differences between the JS and the demo page. Are you referring to [http://fkranenburg.github.io/bootstrap-pincode-input/](url) ?

**Comment by LordZombi** [comment]
No, @fkranenburg I'm referring to this http://www.jqueryscript.net/demo/Custom-Pin-Code-Input-Plugin-with-jQuery-Bootstrap/ and on this demo it works, but with JS in this repo don't.

**Comment by fkranenburg** [comment]
I did not submit this plugin to that site. It was probably [automatically ](http://www.jqueryscript.net/submit/) added (see comments). 

But this bug is a new problem so I will fix it as soon as possible.

**Comment by ajeets1978** [comment]
I think i found what was it. Its because of intentional code checking if its touch device its meant to have only one input box i at the disabled that check for myself and working fine.

**Comment by fkranenburg** [comment]
@ajeets1978 This is fixed. The widget visually renders almost equal on mobile devices now.

**Comment by sanoj26692** [comment]
the bug still exist, it works on desktop but not on mobile device.
![Untitled](https://user-images.githubusercontent.com/7949017/79075102-493d7500-7d0e-11ea-98f1-a7e26f06ccdd.png)

**Comment by mudassir-sultan** [comment]
**Facing same Issue**
please have a look below, 
![image](https://user-images.githubusercontent.com/44690782/93771363-d75f4500-fc36-11ea-8fb8-b290e6f31c57.png)
It  is not working on **mobile screen**,
**how can we fix this one.**

**Comment by fkranenburg** [comment]
@mudassir-sultan can you provide a reproducable example? It would be best to open a new issue.
